/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ComerRouteImport } from './routes/comer'
import { Route as ConocerRouteImport } from './routes/conocer'
import { Route as GuardadosRouteImport } from './routes/guardados'
import { Route as HospedajeRouteImport } from './routes/hospedaje'
import { Route as AuthenticatedResumenRouteImport } from './routes/_authenticated/resumen'
import { Route as AlojamientoIdRouteImport } from './routes/alojamiento.$id'
import { Route as ExperienciaIdRouteImport } from './routes/experiencia.$id'
import { Route as MasterLoginRouteImport } from './routes/master.login'
import { Route as NegocioIdRouteImport } from './routes/negocio.$id'
import { Route as NegocioLoginRouteImport } from './routes/negocio.login'
import { Route as AuthenticatedMiNegocioIndexRouteImport } from './routes/_authenticated/mi-negocio.index'
import { Route as AuthenticatedMiNegocioAlojamientosRouteImport } from './routes/_authenticated/mi-negocio.alojamientos'
import { Route as AuthenticatedMiNegocioComerRouteImport } from './routes/_authenticated/mi-negocio.comer'
import { Route as AuthenticatedMiNegocioCompletarRouteImport } from './routes/_authenticated/mi-negocio.completar'
import { Route as AuthenticatedMiNegocioDisponibilidadRouteImport } from './routes/_authenticated/mi-negocio.disponibilidad'
import { Route as AuthenticatedMiNegocioDisponibilidadRentaRouteImport } from './routes/_authenticated/mi-negocio.disponibilidad-renta'
import { Route as AuthenticatedMiNegocioExperienciasRouteImport } from './routes/_authenticated/mi-negocio.experiencias'
import { Route as AuthenticatedMiNegocioHospedajeRouteImport } from './routes/_authenticated/mi-negocio.hospedaje'
import { Route as AuthenticatedMiNegocioMediosRouteImport } from './routes/_authenticated/mi-negocio.medios'
import { Route as AuthenticatedMiNegocioPedidosRouteImport } from './routes/_authenticated/mi-negocio.pedidos'
import { Route as AuthenticatedMiNegocioProductosRouteImport } from './routes/_authenticated/mi-negocio.productos'
import { Route as AuthenticatedMiNegocioPromocionesRouteImport } from './routes/_authenticated/mi-negocio.promociones'
import { Route as AuthenticatedMiNegocioRentaRouteImport } from './routes/_authenticated/mi-negocio.renta'
import { Route as AuthenticatedMiNegocioReservacionesRouteImport } from './routes/_authenticated/mi-negocio.reservaciones'
import { Route as AuthenticatedMiNegocioSolicitudesHospedajeRouteImport } from './routes/_authenticated/mi-negocio.solicitudes-hospedaje'
import { Route as AuthenticatedMiNegocioSolicitudesRentaRouteImport } from './routes/_authenticated/mi-negocio.solicitudes-renta'
import { Route as AuthenticatedMiNegocioVehiculosRouteImport } from './routes/_authenticated/mi-negocio.vehiculos'
import { Route as AuthenticatedNegociosIndexRouteImport } from './routes/_authenticated/negocios.index'
import { Route as AuthenticatedNegociosIdRouteImport } from './routes/_authenticated/negocios.$id'
import { Route as AuthenticatedNegociosNuevoRouteImport } from './routes/_authenticated/negocios.nuevo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComerRoute = ComerRouteImport.update({
  id: '/comer',
  path: '/comer',
  getParentRoute: () => rootRouteImport,
} as any)
const ConocerRoute = ConocerRouteImport.update({
  id: '/conocer',
  path: '/conocer',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardadosRoute = GuardadosRouteImport.update({
  id: '/guardados',
  path: '/guardados',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedajeRoute = HospedajeRouteImport.update({
  id: '/hospedaje',
  path: '/hospedaje',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumenRoute = AuthenticatedResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AlojamientoIdRoute = AlojamientoIdRouteImport.update({
  id: '/alojamiento/$id',
  path: '/alojamiento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaIdRoute = ExperienciaIdRouteImport.update({
  id: '/experiencia/$id',
  path: '/experiencia/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterLoginRoute = MasterLoginRouteImport.update({
  id: '/master/login',
  path: '/master/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioIdRoute = NegocioIdRouteImport.update({
  id: '/negocio/$id',
  path: '/negocio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioLoginRoute = NegocioLoginRouteImport.update({
  id: '/negocio/login',
  path: '/negocio/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMiNegocioIndexRoute =
  AuthenticatedMiNegocioIndexRouteImport.update({
    id: '/mi-negocio/',
    path: '/mi-negocio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioAlojamientosRoute =
  AuthenticatedMiNegocioAlojamientosRouteImport.update({
    id: '/mi-negocio/alojamientos',
    path: '/mi-negocio/alojamientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioComerRoute =
  AuthenticatedMiNegocioComerRouteImport.update({
    id: '/mi-negocio/comer',
    path: '/mi-negocio/comer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioCompletarRoute =
  AuthenticatedMiNegocioCompletarRouteImport.update({
    id: '/mi-negocio/completar',
    path: '/mi-negocio/completar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioDisponibilidadRoute =
  AuthenticatedMiNegocioDisponibilidadRouteImport.update({
    id: '/mi-negocio/disponibilidad',
    path: '/mi-negocio/disponibilidad',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioDisponibilidadRentaRoute =
  AuthenticatedMiNegocioDisponibilidadRentaRouteImport.update({
    id: '/mi-negocio/disponibilidad-renta',
    path: '/mi-negocio/disponibilidad-renta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioExperienciasRoute =
  AuthenticatedMiNegocioExperienciasRouteImport.update({
    id: '/mi-negocio/experiencias',
    path: '/mi-negocio/experiencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioHospedajeRoute =
  AuthenticatedMiNegocioHospedajeRouteImport.update({
    id: '/mi-negocio/hospedaje',
    path: '/mi-negocio/hospedaje',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioMediosRoute =
  AuthenticatedMiNegocioMediosRouteImport.update({
    id: '/mi-negocio/medios',
    path: '/mi-negocio/medios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioPedidosRoute =
  AuthenticatedMiNegocioPedidosRouteImport.update({
    id: '/mi-negocio/pedidos',
    path: '/mi-negocio/pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioProductosRoute =
  AuthenticatedMiNegocioProductosRouteImport.update({
    id: '/mi-negocio/productos',
    path: '/mi-negocio/productos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioPromocionesRoute =
  AuthenticatedMiNegocioPromocionesRouteImport.update({
    id: '/mi-negocio/promociones',
    path: '/mi-negocio/promociones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioRentaRoute =
  AuthenticatedMiNegocioRentaRouteImport.update({
    id: '/mi-negocio/renta',
    path: '/mi-negocio/renta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioReservacionesRoute =
  AuthenticatedMiNegocioReservacionesRouteImport.update({
    id: '/mi-negocio/reservaciones',
    path: '/mi-negocio/reservaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioSolicitudesHospedajeRoute =
  AuthenticatedMiNegocioSolicitudesHospedajeRouteImport.update({
    id: '/mi-negocio/solicitudes-hospedaje',
    path: '/mi-negocio/solicitudes-hospedaje',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioSolicitudesRentaRoute =
  AuthenticatedMiNegocioSolicitudesRentaRouteImport.update({
    id: '/mi-negocio/solicitudes-renta',
    path: '/mi-negocio/solicitudes-renta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioVehiculosRoute =
  AuthenticatedMiNegocioVehiculosRouteImport.update({
    id: '/mi-negocio/vehiculos',
    path: '/mi-negocio/vehiculos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegociosIndexRoute =
  AuthenticatedNegociosIndexRouteImport.update({
    id: '/negocios/',
    path: '/negocios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegociosIdRoute = AuthenticatedNegociosIdRouteImport.update({
  id: '/negocios/$id',
  path: '/negocios/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNegociosNuevoRoute =
  AuthenticatedNegociosNuevoRouteImport.update({
    id: '/negocios/nuevo',
    path: '/negocios/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/buscar': typeof BuscarRoute
  '/comer': typeof ComerRoute
  '/conocer': typeof ConocerRoute
  '/guardados': typeof GuardadosRoute
  '/hospedaje': typeof HospedajeRoute
  '/resumen': typeof AuthenticatedResumenRoute
  '/alojamiento/$id': typeof AlojamientoIdRoute
  '/experiencia/$id': typeof ExperienciaIdRoute
  '/master/login': typeof MasterLoginRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/negocio/login': typeof NegocioLoginRoute
  '/mi-negocio/alojamientos': typeof AuthenticatedMiNegocioAlojamientosRoute
  '/mi-negocio/comer': typeof AuthenticatedMiNegocioComerRoute
  '/mi-negocio/completar': typeof AuthenticatedMiNegocioCompletarRoute
  '/mi-negocio/disponibilidad': typeof AuthenticatedMiNegocioDisponibilidadRoute
  '/mi-negocio/disponibilidad-renta': typeof AuthenticatedMiNegocioDisponibilidadRentaRoute
  '/mi-negocio/experiencias': typeof AuthenticatedMiNegocioExperienciasRoute
  '/mi-negocio/hospedaje': typeof AuthenticatedMiNegocioHospedajeRoute
  '/mi-negocio/medios': typeof AuthenticatedMiNegocioMediosRoute
  '/mi-negocio/pedidos': typeof AuthenticatedMiNegocioPedidosRoute
  '/mi-negocio/productos': typeof AuthenticatedMiNegocioProductosRoute
  '/mi-negocio/promociones': typeof AuthenticatedMiNegocioPromocionesRoute
  '/mi-negocio/renta': typeof AuthenticatedMiNegocioRentaRoute
  '/mi-negocio/reservaciones': typeof AuthenticatedMiNegocioReservacionesRoute
  '/mi-negocio/solicitudes-hospedaje': typeof AuthenticatedMiNegocioSolicitudesHospedajeRoute
  '/mi-negocio/solicitudes-renta': typeof AuthenticatedMiNegocioSolicitudesRentaRoute
  '/mi-negocio/vehiculos': typeof AuthenticatedMiNegocioVehiculosRoute
  '/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/negocios/nuevo': typeof AuthenticatedNegociosNuevoRoute
  '/mi-negocio/': typeof AuthenticatedMiNegocioIndexRoute
  '/negocios/': typeof AuthenticatedNegociosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/buscar': typeof BuscarRoute
  '/comer': typeof ComerRoute
  '/conocer': typeof ConocerRoute
  '/guardados': typeof GuardadosRoute
  '/hospedaje': typeof HospedajeRoute
  '/resumen': typeof AuthenticatedResumenRoute
  '/alojamiento/$id': typeof AlojamientoIdRoute
  '/experiencia/$id': typeof ExperienciaIdRoute
  '/master/login': typeof MasterLoginRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/negocio/login': typeof NegocioLoginRoute
  '/mi-negocio/alojamientos': typeof AuthenticatedMiNegocioAlojamientosRoute
  '/mi-negocio/comer': typeof AuthenticatedMiNegocioComerRoute
  '/mi-negocio/completar': typeof AuthenticatedMiNegocioCompletarRoute
  '/mi-negocio/disponibilidad': typeof AuthenticatedMiNegocioDisponibilidadRoute
  '/mi-negocio/disponibilidad-renta': typeof AuthenticatedMiNegocioDisponibilidadRentaRoute
  '/mi-negocio/experiencias': typeof AuthenticatedMiNegocioExperienciasRoute
  '/mi-negocio/hospedaje': typeof AuthenticatedMiNegocioHospedajeRoute
  '/mi-negocio/medios': typeof AuthenticatedMiNegocioMediosRoute
  '/mi-negocio/pedidos': typeof AuthenticatedMiNegocioPedidosRoute
  '/mi-negocio/productos': typeof AuthenticatedMiNegocioProductosRoute
  '/mi-negocio/promociones': typeof AuthenticatedMiNegocioPromocionesRoute
  '/mi-negocio/renta': typeof AuthenticatedMiNegocioRentaRoute
  '/mi-negocio/reservaciones': typeof AuthenticatedMiNegocioReservacionesRoute
  '/mi-negocio/solicitudes-hospedaje': typeof AuthenticatedMiNegocioSolicitudesHospedajeRoute
  '/mi-negocio/solicitudes-renta': typeof AuthenticatedMiNegocioSolicitudesRentaRoute
  '/mi-negocio/vehiculos': typeof AuthenticatedMiNegocioVehiculosRoute
  '/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/negocios/nuevo': typeof AuthenticatedNegociosNuevoRoute
  '/mi-negocio': typeof AuthenticatedMiNegocioIndexRoute
  '/negocios': typeof AuthenticatedNegociosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acceso': typeof AccesoRoute
  '/buscar': typeof BuscarRoute
  '/comer': typeof ComerRoute
  '/conocer': typeof ConocerRoute
  '/guardados': typeof GuardadosRoute
  '/hospedaje': typeof HospedajeRoute
  '/_authenticated/resumen': typeof AuthenticatedResumenRoute
  '/alojamiento/$id': typeof AlojamientoIdRoute
  '/experiencia/$id': typeof ExperienciaIdRoute
  '/master/login': typeof MasterLoginRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/negocio/login': typeof NegocioLoginRoute
  '/_authenticated/mi-negocio/alojamientos': typeof AuthenticatedMiNegocioAlojamientosRoute
  '/_authenticated/mi-negocio/comer': typeof AuthenticatedMiNegocioComerRoute
  '/_authenticated/mi-negocio/completar': typeof AuthenticatedMiNegocioCompletarRoute
  '/_authenticated/mi-negocio/disponibilidad': typeof AuthenticatedMiNegocioDisponibilidadRoute
  '/_authenticated/mi-negocio/disponibilidad-renta': typeof AuthenticatedMiNegocioDisponibilidadRentaRoute
  '/_authenticated/mi-negocio/experiencias': typeof AuthenticatedMiNegocioExperienciasRoute
  '/_authenticated/mi-negocio/hospedaje': typeof AuthenticatedMiNegocioHospedajeRoute
  '/_authenticated/mi-negocio/medios': typeof AuthenticatedMiNegocioMediosRoute
  '/_authenticated/mi-negocio/pedidos': typeof AuthenticatedMiNegocioPedidosRoute
  '/_authenticated/mi-negocio/productos': typeof AuthenticatedMiNegocioProductosRoute
  '/_authenticated/mi-negocio/promociones': typeof AuthenticatedMiNegocioPromocionesRoute
  '/_authenticated/mi-negocio/renta': typeof AuthenticatedMiNegocioRentaRoute
  '/_authenticated/mi-negocio/reservaciones': typeof AuthenticatedMiNegocioReservacionesRoute
  '/_authenticated/mi-negocio/solicitudes-hospedaje': typeof AuthenticatedMiNegocioSolicitudesHospedajeRoute
  '/_authenticated/mi-negocio/solicitudes-renta': typeof AuthenticatedMiNegocioSolicitudesRentaRoute
  '/_authenticated/mi-negocio/vehiculos': typeof AuthenticatedMiNegocioVehiculosRoute
  '/_authenticated/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/_authenticated/negocios/nuevo': typeof AuthenticatedNegociosNuevoRoute
  '/_authenticated/mi-negocio/': typeof AuthenticatedMiNegocioIndexRoute
  '/_authenticated/negocios/': typeof AuthenticatedNegociosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/buscar'
    | '/comer'
    | '/conocer'
    | '/guardados'
    | '/hospedaje'
    | '/resumen'
    | '/alojamiento/$id'
    | '/experiencia/$id'
    | '/master/login'
    | '/negocio/$id'
    | '/negocio/login'
    | '/mi-negocio/alojamientos'
    | '/mi-negocio/comer'
    | '/mi-negocio/completar'
    | '/mi-negocio/disponibilidad'
    | '/mi-negocio/disponibilidad-renta'
    | '/mi-negocio/experiencias'
    | '/mi-negocio/hospedaje'
    | '/mi-negocio/medios'
    | '/mi-negocio/pedidos'
    | '/mi-negocio/productos'
    | '/mi-negocio/promociones'
    | '/mi-negocio/renta'
    | '/mi-negocio/reservaciones'
    | '/mi-negocio/solicitudes-hospedaje'
    | '/mi-negocio/solicitudes-renta'
    | '/mi-negocio/vehiculos'
    | '/negocios/$id'
    | '/negocios/nuevo'
    | '/mi-negocio/'
    | '/negocios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/buscar'
    | '/comer'
    | '/conocer'
    | '/guardados'
    | '/hospedaje'
    | '/resumen'
    | '/alojamiento/$id'
    | '/experiencia/$id'
    | '/master/login'
    | '/negocio/$id'
    | '/negocio/login'
    | '/mi-negocio/alojamientos'
    | '/mi-negocio/comer'
    | '/mi-negocio/completar'
    | '/mi-negocio/disponibilidad'
    | '/mi-negocio/disponibilidad-renta'
    | '/mi-negocio/experiencias'
    | '/mi-negocio/hospedaje'
    | '/mi-negocio/medios'
    | '/mi-negocio/pedidos'
    | '/mi-negocio/productos'
    | '/mi-negocio/promociones'
    | '/mi-negocio/renta'
    | '/mi-negocio/reservaciones'
    | '/mi-negocio/solicitudes-hospedaje'
    | '/mi-negocio/solicitudes-renta'
    | '/mi-negocio/vehiculos'
    | '/negocios/$id'
    | '/negocios/nuevo'
    | '/mi-negocio'
    | '/negocios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acceso'
    | '/buscar'
    | '/comer'
    | '/conocer'
    | '/guardados'
    | '/hospedaje'
    | '/_authenticated/resumen'
    | '/alojamiento/$id'
    | '/experiencia/$id'
    | '/master/login'
    | '/negocio/$id'
    | '/negocio/login'
    | '/_authenticated/mi-negocio/alojamientos'
    | '/_authenticated/mi-negocio/comer'
    | '/_authenticated/mi-negocio/completar'
    | '/_authenticated/mi-negocio/disponibilidad'
    | '/_authenticated/mi-negocio/disponibilidad-renta'
    | '/_authenticated/mi-negocio/experiencias'
    | '/_authenticated/mi-negocio/hospedaje'
    | '/_authenticated/mi-negocio/medios'
    | '/_authenticated/mi-negocio/pedidos'
    | '/_authenticated/mi-negocio/productos'
    | '/_authenticated/mi-negocio/promociones'
    | '/_authenticated/mi-negocio/renta'
    | '/_authenticated/mi-negocio/reservaciones'
    | '/_authenticated/mi-negocio/solicitudes-hospedaje'
    | '/_authenticated/mi-negocio/solicitudes-renta'
    | '/_authenticated/mi-negocio/vehiculos'
    | '/_authenticated/negocios/$id'
    | '/_authenticated/negocios/nuevo'
    | '/_authenticated/mi-negocio/'
    | '/_authenticated/negocios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccesoRoute: typeof AccesoRoute
  BuscarRoute: typeof BuscarRoute
  ComerRoute: typeof ComerRoute
  ConocerRoute: typeof ConocerRoute
  GuardadosRoute: typeof GuardadosRoute
  HospedajeRoute: typeof HospedajeRoute
  AlojamientoIdRoute: typeof AlojamientoIdRoute
  ExperienciaIdRoute: typeof ExperienciaIdRoute
  MasterLoginRoute: typeof MasterLoginRoute
  NegocioIdRoute: typeof NegocioIdRoute
  NegocioLoginRoute: typeof NegocioLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comer': {
      id: '/comer'
      path: '/comer'
      fullPath: '/comer'
      preLoaderRoute: typeof ComerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conocer': {
      id: '/conocer'
      path: '/conocer'
      fullPath: '/conocer'
      preLoaderRoute: typeof ConocerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardados': {
      id: '/guardados'
      path: '/guardados'
      fullPath: '/guardados'
      preLoaderRoute: typeof GuardadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedaje': {
      id: '/hospedaje'
      path: '/hospedaje'
      fullPath: '/hospedaje'
      preLoaderRoute: typeof HospedajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resumen': {
      id: '/_authenticated/resumen'
      path: '/resumen'
      fullPath: '/resumen'
      preLoaderRoute: typeof AuthenticatedResumenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/alojamiento/$id': {
      id: '/alojamiento/$id'
      path: '/alojamiento/$id'
      fullPath: '/alojamiento/$id'
      preLoaderRoute: typeof AlojamientoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia/$id': {
      id: '/experiencia/$id'
      path: '/experiencia/$id'
      fullPath: '/experiencia/$id'
      preLoaderRoute: typeof ExperienciaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/login': {
      id: '/master/login'
      path: '/master/login'
      fullPath: '/master/login'
      preLoaderRoute: typeof MasterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio/$id': {
      id: '/negocio/$id'
      path: '/negocio/$id'
      fullPath: '/negocio/$id'
      preLoaderRoute: typeof NegocioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio/login': {
      id: '/negocio/login'
      path: '/negocio/login'
      fullPath: '/negocio/login'
      preLoaderRoute: typeof NegocioLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mi-negocio/': {
      id: '/_authenticated/mi-negocio/'
      path: '/mi-negocio'
      fullPath: '/mi-negocio/'
      preLoaderRoute: typeof AuthenticatedMiNegocioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/alojamientos': {
      id: '/_authenticated/mi-negocio/alojamientos'
      path: '/mi-negocio/alojamientos'
      fullPath: '/mi-negocio/alojamientos'
      preLoaderRoute: typeof AuthenticatedMiNegocioAlojamientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/comer': {
      id: '/_authenticated/mi-negocio/comer'
      path: '/mi-negocio/comer'
      fullPath: '/mi-negocio/comer'
      preLoaderRoute: typeof AuthenticatedMiNegocioComerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/completar': {
      id: '/_authenticated/mi-negocio/completar'
      path: '/mi-negocio/completar'
      fullPath: '/mi-negocio/completar'
      preLoaderRoute: typeof AuthenticatedMiNegocioCompletarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/disponibilidad': {
      id: '/_authenticated/mi-negocio/disponibilidad'
      path: '/mi-negocio/disponibilidad'
      fullPath: '/mi-negocio/disponibilidad'
      preLoaderRoute: typeof AuthenticatedMiNegocioDisponibilidadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/disponibilidad-renta': {
      id: '/_authenticated/mi-negocio/disponibilidad-renta'
      path: '/mi-negocio/disponibilidad-renta'
      fullPath: '/mi-negocio/disponibilidad-renta'
      preLoaderRoute: typeof AuthenticatedMiNegocioDisponibilidadRentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/experiencias': {
      id: '/_authenticated/mi-negocio/experiencias'
      path: '/mi-negocio/experiencias'
      fullPath: '/mi-negocio/experiencias'
      preLoaderRoute: typeof AuthenticatedMiNegocioExperienciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/hospedaje': {
      id: '/_authenticated/mi-negocio/hospedaje'
      path: '/mi-negocio/hospedaje'
      fullPath: '/mi-negocio/hospedaje'
      preLoaderRoute: typeof AuthenticatedMiNegocioHospedajeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/medios': {
      id: '/_authenticated/mi-negocio/medios'
      path: '/mi-negocio/medios'
      fullPath: '/mi-negocio/medios'
      preLoaderRoute: typeof AuthenticatedMiNegocioMediosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/pedidos': {
      id: '/_authenticated/mi-negocio/pedidos'
      path: '/mi-negocio/pedidos'
      fullPath: '/mi-negocio/pedidos'
      preLoaderRoute: typeof AuthenticatedMiNegocioPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/productos': {
      id: '/_authenticated/mi-negocio/productos'
      path: '/mi-negocio/productos'
      fullPath: '/mi-negocio/productos'
      preLoaderRoute: typeof AuthenticatedMiNegocioProductosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/promociones': {
      id: '/_authenticated/mi-negocio/promociones'
      path: '/mi-negocio/promociones'
      fullPath: '/mi-negocio/promociones'
      preLoaderRoute: typeof AuthenticatedMiNegocioPromocionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/renta': {
      id: '/_authenticated/mi-negocio/renta'
      path: '/mi-negocio/renta'
      fullPath: '/mi-negocio/renta'
      preLoaderRoute: typeof AuthenticatedMiNegocioRentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/reservaciones': {
      id: '/_authenticated/mi-negocio/reservaciones'
      path: '/mi-negocio/reservaciones'
      fullPath: '/mi-negocio/reservaciones'
      preLoaderRoute: typeof AuthenticatedMiNegocioReservacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/solicitudes-hospedaje': {
      id: '/_authenticated/mi-negocio/solicitudes-hospedaje'
      path: '/mi-negocio/solicitudes-hospedaje'
      fullPath: '/mi-negocio/solicitudes-hospedaje'
      preLoaderRoute: typeof AuthenticatedMiNegocioSolicitudesHospedajeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/solicitudes-renta': {
      id: '/_authenticated/mi-negocio/solicitudes-renta'
      path: '/mi-negocio/solicitudes-renta'
      fullPath: '/mi-negocio/solicitudes-renta'
      preLoaderRoute: typeof AuthenticatedMiNegocioSolicitudesRentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/vehiculos': {
      id: '/_authenticated/mi-negocio/vehiculos'
      path: '/mi-negocio/vehiculos'
      fullPath: '/mi-negocio/vehiculos'
      preLoaderRoute: typeof AuthenticatedMiNegocioVehiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocios/': {
      id: '/_authenticated/negocios/'
      path: '/negocios'
      fullPath: '/negocios/'
      preLoaderRoute: typeof AuthenticatedNegociosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocios/$id': {
      id: '/_authenticated/negocios/$id'
      path: '/negocios/$id'
      fullPath: '/negocios/$id'
      preLoaderRoute: typeof AuthenticatedNegociosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocios/nuevo': {
      id: '/_authenticated/negocios/nuevo'
      path: '/negocios/nuevo'
      fullPath: '/negocios/nuevo'
      preLoaderRoute: typeof AuthenticatedNegociosNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedResumenRoute: typeof AuthenticatedResumenRoute
  AuthenticatedMiNegocioAlojamientosRoute: typeof AuthenticatedMiNegocioAlojamientosRoute
  AuthenticatedMiNegocioComerRoute: typeof AuthenticatedMiNegocioComerRoute
  AuthenticatedMiNegocioCompletarRoute: typeof AuthenticatedMiNegocioCompletarRoute
  AuthenticatedMiNegocioDisponibilidadRoute: typeof AuthenticatedMiNegocioDisponibilidadRoute
  AuthenticatedMiNegocioDisponibilidadRentaRoute: typeof AuthenticatedMiNegocioDisponibilidadRentaRoute
  AuthenticatedMiNegocioExperienciasRoute: typeof AuthenticatedMiNegocioExperienciasRoute
  AuthenticatedMiNegocioHospedajeRoute: typeof AuthenticatedMiNegocioHospedajeRoute
  AuthenticatedMiNegocioMediosRoute: typeof AuthenticatedMiNegocioMediosRoute
  AuthenticatedMiNegocioPedidosRoute: typeof AuthenticatedMiNegocioPedidosRoute
  AuthenticatedMiNegocioProductosRoute: typeof AuthenticatedMiNegocioProductosRoute
  AuthenticatedMiNegocioPromocionesRoute: typeof AuthenticatedMiNegocioPromocionesRoute
  AuthenticatedMiNegocioRentaRoute: typeof AuthenticatedMiNegocioRentaRoute
  AuthenticatedMiNegocioReservacionesRoute: typeof AuthenticatedMiNegocioReservacionesRoute
  AuthenticatedMiNegocioSolicitudesHospedajeRoute: typeof AuthenticatedMiNegocioSolicitudesHospedajeRoute
  AuthenticatedMiNegocioSolicitudesRentaRoute: typeof AuthenticatedMiNegocioSolicitudesRentaRoute
  AuthenticatedMiNegocioVehiculosRoute: typeof AuthenticatedMiNegocioVehiculosRoute
  AuthenticatedNegociosIdRoute: typeof AuthenticatedNegociosIdRoute
  AuthenticatedNegociosNuevoRoute: typeof AuthenticatedNegociosNuevoRoute
  AuthenticatedMiNegocioIndexRoute: typeof AuthenticatedMiNegocioIndexRoute
  AuthenticatedNegociosIndexRoute: typeof AuthenticatedNegociosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedResumenRoute: AuthenticatedResumenRoute,
  AuthenticatedMiNegocioAlojamientosRoute:
    AuthenticatedMiNegocioAlojamientosRoute,
  AuthenticatedMiNegocioComerRoute: AuthenticatedMiNegocioComerRoute,
  AuthenticatedMiNegocioCompletarRoute: AuthenticatedMiNegocioCompletarRoute,
  AuthenticatedMiNegocioDisponibilidadRoute:
    AuthenticatedMiNegocioDisponibilidadRoute,
  AuthenticatedMiNegocioDisponibilidadRentaRoute:
    AuthenticatedMiNegocioDisponibilidadRentaRoute,
  AuthenticatedMiNegocioExperienciasRoute:
    AuthenticatedMiNegocioExperienciasRoute,
  AuthenticatedMiNegocioHospedajeRoute: AuthenticatedMiNegocioHospedajeRoute,
  AuthenticatedMiNegocioMediosRoute: AuthenticatedMiNegocioMediosRoute,
  AuthenticatedMiNegocioPedidosRoute: AuthenticatedMiNegocioPedidosRoute,
  AuthenticatedMiNegocioProductosRoute: AuthenticatedMiNegocioProductosRoute,
  AuthenticatedMiNegocioPromocionesRoute:
    AuthenticatedMiNegocioPromocionesRoute,
  AuthenticatedMiNegocioRentaRoute: AuthenticatedMiNegocioRentaRoute,
  AuthenticatedMiNegocioReservacionesRoute:
    AuthenticatedMiNegocioReservacionesRoute,
  AuthenticatedMiNegocioSolicitudesHospedajeRoute:
    AuthenticatedMiNegocioSolicitudesHospedajeRoute,
  AuthenticatedMiNegocioSolicitudesRentaRoute:
    AuthenticatedMiNegocioSolicitudesRentaRoute,
  AuthenticatedMiNegocioVehiculosRoute: AuthenticatedMiNegocioVehiculosRoute,
  AuthenticatedNegociosIdRoute: AuthenticatedNegociosIdRoute,
  AuthenticatedNegociosNuevoRoute: AuthenticatedNegociosNuevoRoute,
  AuthenticatedMiNegocioIndexRoute: AuthenticatedMiNegocioIndexRoute,
  AuthenticatedNegociosIndexRoute: AuthenticatedNegociosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccesoRoute: AccesoRoute,
  BuscarRoute: BuscarRoute,
  ComerRoute: ComerRoute,
  ConocerRoute: ConocerRoute,
  GuardadosRoute: GuardadosRoute,
  HospedajeRoute: HospedajeRoute,
  AlojamientoIdRoute: AlojamientoIdRoute,
  ExperienciaIdRoute: ExperienciaIdRoute,
  MasterLoginRoute: MasterLoginRoute,
  NegocioIdRoute: NegocioIdRoute,
  NegocioLoginRoute: NegocioLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
