/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as GuardadosRouteImport } from './routes/guardados'
import { Route as AuthenticatedResumenRouteImport } from './routes/_authenticated/resumen'
import { Route as NegocioIdRouteImport } from './routes/negocio.$id'
import { Route as AuthenticatedMiNegocioIndexRouteImport } from './routes/_authenticated/mi-negocio.index'
import { Route as AuthenticatedMiNegocioCompletarRouteImport } from './routes/_authenticated/mi-negocio.completar'
import { Route as AuthenticatedNegociosIndexRouteImport } from './routes/_authenticated/negocios.index'
import { Route as AuthenticatedNegociosIdRouteImport } from './routes/_authenticated/negocios.$id'
import { Route as AuthenticatedNegociosNuevoRouteImport } from './routes/_authenticated/negocios.nuevo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardadosRoute = GuardadosRouteImport.update({
  id: '/guardados',
  path: '/guardados',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumenRoute = AuthenticatedResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const NegocioIdRoute = NegocioIdRouteImport.update({
  id: '/negocio/$id',
  path: '/negocio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMiNegocioIndexRoute =
  AuthenticatedMiNegocioIndexRouteImport.update({
    id: '/mi-negocio/',
    path: '/mi-negocio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiNegocioCompletarRoute =
  AuthenticatedMiNegocioCompletarRouteImport.update({
    id: '/mi-negocio/completar',
    path: '/mi-negocio/completar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegociosIndexRoute =
  AuthenticatedNegociosIndexRouteImport.update({
    id: '/negocios/',
    path: '/negocios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegociosIdRoute = AuthenticatedNegociosIdRouteImport.update({
  id: '/negocios/$id',
  path: '/negocios/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNegociosNuevoRoute =
  AuthenticatedNegociosNuevoRouteImport.update({
    id: '/negocios/nuevo',
    path: '/negocios/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/buscar': typeof BuscarRoute
  '/guardados': typeof GuardadosRoute
  '/resumen': typeof AuthenticatedResumenRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/mi-negocio/completar': typeof AuthenticatedMiNegocioCompletarRoute
  '/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/negocios/nuevo': typeof AuthenticatedNegociosNuevoRoute
  '/mi-negocio/': typeof AuthenticatedMiNegocioIndexRoute
  '/negocios/': typeof AuthenticatedNegociosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/buscar': typeof BuscarRoute
  '/guardados': typeof GuardadosRoute
  '/resumen': typeof AuthenticatedResumenRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/mi-negocio/completar': typeof AuthenticatedMiNegocioCompletarRoute
  '/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/negocios/nuevo': typeof AuthenticatedNegociosNuevoRoute
  '/mi-negocio': typeof AuthenticatedMiNegocioIndexRoute
  '/negocios': typeof AuthenticatedNegociosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acceso': typeof AccesoRoute
  '/buscar': typeof BuscarRoute
  '/guardados': typeof GuardadosRoute
  '/_authenticated/resumen': typeof AuthenticatedResumenRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/_authenticated/mi-negocio/completar': typeof AuthenticatedMiNegocioCompletarRoute
  '/_authenticated/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/_authenticated/negocios/nuevo': typeof AuthenticatedNegociosNuevoRoute
  '/_authenticated/mi-negocio/': typeof AuthenticatedMiNegocioIndexRoute
  '/_authenticated/negocios/': typeof AuthenticatedNegociosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/buscar'
    | '/guardados'
    | '/resumen'
    | '/negocio/$id'
    | '/mi-negocio/completar'
    | '/negocios/$id'
    | '/negocios/nuevo'
    | '/mi-negocio/'
    | '/negocios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/buscar'
    | '/guardados'
    | '/resumen'
    | '/negocio/$id'
    | '/mi-negocio/completar'
    | '/negocios/$id'
    | '/negocios/nuevo'
    | '/mi-negocio'
    | '/negocios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acceso'
    | '/buscar'
    | '/guardados'
    | '/_authenticated/resumen'
    | '/negocio/$id'
    | '/_authenticated/mi-negocio/completar'
    | '/_authenticated/negocios/$id'
    | '/_authenticated/negocios/nuevo'
    | '/_authenticated/mi-negocio/'
    | '/_authenticated/negocios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccesoRoute: typeof AccesoRoute
  BuscarRoute: typeof BuscarRoute
  GuardadosRoute: typeof GuardadosRoute
  NegocioIdRoute: typeof NegocioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardados': {
      id: '/guardados'
      path: '/guardados'
      fullPath: '/guardados'
      preLoaderRoute: typeof GuardadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resumen': {
      id: '/_authenticated/resumen'
      path: '/resumen'
      fullPath: '/resumen'
      preLoaderRoute: typeof AuthenticatedResumenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/negocio/$id': {
      id: '/negocio/$id'
      path: '/negocio/$id'
      fullPath: '/negocio/$id'
      preLoaderRoute: typeof NegocioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mi-negocio/': {
      id: '/_authenticated/mi-negocio/'
      path: '/mi-negocio'
      fullPath: '/mi-negocio/'
      preLoaderRoute: typeof AuthenticatedMiNegocioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-negocio/completar': {
      id: '/_authenticated/mi-negocio/completar'
      path: '/mi-negocio/completar'
      fullPath: '/mi-negocio/completar'
      preLoaderRoute: typeof AuthenticatedMiNegocioCompletarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocios/': {
      id: '/_authenticated/negocios/'
      path: '/negocios'
      fullPath: '/negocios/'
      preLoaderRoute: typeof AuthenticatedNegociosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocios/$id': {
      id: '/_authenticated/negocios/$id'
      path: '/negocios/$id'
      fullPath: '/negocios/$id'
      preLoaderRoute: typeof AuthenticatedNegociosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocios/nuevo': {
      id: '/_authenticated/negocios/nuevo'
      path: '/negocios/nuevo'
      fullPath: '/negocios/nuevo'
      preLoaderRoute: typeof AuthenticatedNegociosNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedResumenRoute: typeof AuthenticatedResumenRoute
  AuthenticatedMiNegocioCompletarRoute: typeof AuthenticatedMiNegocioCompletarRoute
  AuthenticatedNegociosIdRoute: typeof AuthenticatedNegociosIdRoute
  AuthenticatedNegociosNuevoRoute: typeof AuthenticatedNegociosNuevoRoute
  AuthenticatedMiNegocioIndexRoute: typeof AuthenticatedMiNegocioIndexRoute
  AuthenticatedNegociosIndexRoute: typeof AuthenticatedNegociosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedResumenRoute: AuthenticatedResumenRoute,
  AuthenticatedMiNegocioCompletarRoute: AuthenticatedMiNegocioCompletarRoute,
  AuthenticatedNegociosIdRoute: AuthenticatedNegociosIdRoute,
  AuthenticatedNegociosNuevoRoute: AuthenticatedNegociosNuevoRoute,
  AuthenticatedMiNegocioIndexRoute: AuthenticatedMiNegocioIndexRoute,
  AuthenticatedNegociosIndexRoute: AuthenticatedNegociosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccesoRoute: AccesoRoute,
  BuscarRoute: BuscarRoute,
  GuardadosRoute: GuardadosRoute,
  NegocioIdRoute: NegocioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
